apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  ports:
  - port: 8070
    targetPort: 80
  selector:
    app: {{ .Release.Name }}
  type: LoadBalancer
